### ISSUE TITLE
Unable to Pull Singularity Image from Specified URL

### ISSUE THREAD

**Issue by Romisaa-Ali** [Daffan/ros_jackal#5]
Issue Description:
I am trying to pull a Singularity image from the URL library://zifanxu/ros_jackal_image/image:latest, but I am encountering issues. When I search for this image using Singularity, it appears not to be available for the amd64 architecture.
thank you,

R.

**Comment by Usaywook** [comment]
I also could not pull a Singularity image when implementing this command
```
python3 train.py --config configs/e2e_default_TD3.yaml
```

I got this error 

```
>>>>>>>> Loading the configuration from configs/e2e_default_TD3.yaml
>>>>>>>> Creating the environments
/usr/local/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
>>>>>>>> Initializing the policy
    >>>> Running on device cuda:0
>>>>>>>> Start training
    >>>> Saving to logging/motion_control_continuous_laser-v0/TD3/2023_08_29_01_04/a9b6
    >>>> initialized logging
    >>>> Pre-collect experience
singularity pull --name local_buffer/nav_benchmark.sif library://zifanxu/ros_jackal_image/image:latest
INFO:    Using cached image

WARNING: integrity: signature not found for object group 1

WARNING: Skipping container verification

Traceback (most recent call last):
  File "/root/docker-workspace/ssd256/jackal_ws/src/ros_jackal/train.py", line 304, in <module>
    train(env, policy, replay_buffer, config)
  File "/root/docker-workspace/ssd256/jackal_ws/src/ros_jackal/train.py", line 214, in train
    collector.collect(n_steps=training_config['pre_collect'])
  File "/root/docker-workspace/ssd256/jackal_ws/src/ros_jackal/rl_algos/collector.py", line 180, in collect
    print(o[0])
KeyError: 0
```

I understood the image was saved as cache in ~/.singularity.
However, after runing this command,

```
./singularity_run.sh local_buffer/image:latest.sif python3 test_env.py
```

I got this error
```
ERROR  : Requesting capability set 0x000001ffffffffff while permitted capability set is 0x0000003fffffffff
```

**Comment by Daffan** [comment]
Hi Usaywook,

Would you be able to pull an image using a separate command as follows?
`singularity pull --name <PATH_TO_THIS_REPO>/local_buffer/image:latest.sif library://zifanxu/ros_jackal_image/image:latest`

After running this command, you should be able to see a file `<PATH_TO_THIS_REPO>/local_buffer/image:latest.sif `.

The image is not save in `~/.singularity`, there might be some cache there though.

Let me know, thanks!
